"""
Module 6 — AI Natural Language Search
======================================
Safety guard for SQL generated by an LLM.

The LLM only ever proposes SQL — it never executes it directly.
Every generated statement must pass through `validate_sql()` before we
run it against the database. This keeps a hostile or confused prompt
(e.g. "delete all students" or a prompt-injection buried in an Excel
upload) from ever producing a write, a multi-statement payload, or a
query outside the tables IQAC actually wants searchable.
"""
import re

# Tables the AI is allowed to read. Deliberately excludes users,
# refresh_tokens, upload_jobs, and ai_query_logs — internal/auth tables
# that have no business being reachable from a natural-language search box.
ALLOWED_TABLES: set[str] = {
    "departments",
    "programs",
    "faculty",
    "students",
    "research_publications",
    "patents",
    "funded_projects",
    "placements",
    "higher_studies",
    "infrastructure",
    "budgets",
    "mous",
    "events",
    "consultancies",
    "energy_consumption",
    "water_consumption",
    "waste_management",
    "green_initiatives",
    "awards",
    "accreditations",
    "sdg_activities",
}

# Statement types / keywords that must never appear in a generated query.
_FORBIDDEN_KEYWORDS = (
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE",
    "GRANT", "REVOKE", "EXECUTE", "EXEC", "MERGE", "CALL", "COPY",
    "ATTACH", "DETACH", "PRAGMA", "VACUUM", "REPLACE", "INTO OUTFILE",
    "GRANT", "SET ", "DO $$", "LISTEN", "NOTIFY", "REFRESH MATERIALIZED",
)

_TABLE_REF_RE = re.compile(r"\b(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)", re.IGNORECASE)


class SQLGuardError(Exception):
    """Raised when generated SQL fails the safety check."""


def _strip_code_fences(sql: str) -> str:
    sql = sql.strip()
    # Remove ```sql ... ``` or ``` ... ``` fences if the LLM added them
    sql = re.sub(r"^```(?:sql)?\s*", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\s*```$", "", sql)
    return sql.strip()


def validate_sql(raw_sql: str, row_limit: int) -> str:
    """
    Validates and normalizes a single SQL statement.
    Returns the (possibly LIMIT-appended) SQL string if safe.
    Raises SQLGuardError otherwise.
    """
    sql = _strip_code_fences(raw_sql)

    if not sql:
        raise SQLGuardError("The AI did not return a SQL statement.")

    # Reject multiple statements (a stray semicolon followed by more SQL)
    stripped = sql.rstrip(";").strip()
    if ";" in stripped:
        raise SQLGuardError("Only a single SQL statement is allowed.")
    sql = stripped

    # Must be a read-only SELECT (or a WITH ... SELECT CTE)
    first_word = sql.strip().split(None, 1)[0].upper() if sql.strip() else ""
    if first_word not in ("SELECT", "WITH"):
        raise SQLGuardError("Only SELECT queries are permitted.")

    upper_sql = sql.upper()
    for keyword in _FORBIDDEN_KEYWORDS:
        if keyword in upper_sql:
            raise SQLGuardError(f"Generated SQL contains a disallowed keyword: '{keyword.strip()}'.")

    if " INTO " in f" {upper_sql} ":
        raise SQLGuardError("SELECT ... INTO is not permitted.")

    # Verify every referenced table is on the whitelist
    referenced = {m.group(1).lower() for m in _TABLE_REF_RE.finditer(sql)}
    if not referenced:
        raise SQLGuardError("Could not identify any table in the generated query.")

    unknown = referenced - ALLOWED_TABLES
    if unknown:
        raise SQLGuardError(
            f"Query references table(s) not permitted for AI search: {', '.join(sorted(unknown))}."
        )

    # Enforce a row cap — append LIMIT if the LLM didn't include one,
    # or the one it did include exceeds our cap.
    limit_match = re.search(r"\bLIMIT\s+(\d+)\b", sql, re.IGNORECASE)
    if limit_match:
        existing_limit = int(limit_match.group(1))
        if existing_limit > row_limit:
            sql = re.sub(r"\bLIMIT\s+\d+\b", f"LIMIT {row_limit}", sql, flags=re.IGNORECASE)
    else:
        sql = f"{sql}\nLIMIT {row_limit}"

    return sql
